default: &default
  adapter: postgresql
  encoding: unicode
  databasae: postgres
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: postgres
  password:
  host: db

development:

  test:
  <<: *default
  database: myapp_test

